apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default-namespace-mtls
  namespace: default
spec:
  mtls:
    mode: STRICT

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: details-mtls
  namespace: default
spec:
  host: details.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: details-2-mtls
  namespace: default
spec:
  host: details-2.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL


